remote_theme: chrisrhymes/bulma-clean-theme

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

footer_menu: footer

navbar: is-dark
